:datasett: Kartkontroll
:versjon: 1.0
:publisert: 2022-05-05
:skjema-versjon: 1.0

// All informasjon i hode over denne linja må fylles ut for hvert datasett. Linjene under settes av de gitte variablene over og i adoc_parametere.adoc
include::../felles/adoc_parametere.adoc[]
= SOSI produktspesifikasjon: {datasett}
Geovekst
{versjon}, 2022-05-05

include::../felles/dokument_metadata.adoc[]


== Innledning, historikk og endringslogg

=== Innledning

Produktspesifikasjon {datasett} {versjon} er laget for å ha en dokumentert og enhetlig måte å gi tilbakemelding til leverandør av kartdata nå det oppdages avvik i kontrollen av dataene hos oppdragsgiver. Produktspesifikasjonen baserer seg på at kravene til dataene er satt i henhold til rammeverket definert av standarden Geodatakvalitet <<G>>.

Produktspesifikasjonen er utarbeidet av Kartverket spesielt med tanke på bruk i FKB-kartleggingsprosjekter der Kartverket - på vegne av Geovekst-samarbeidet - er oppdragsgiver og kontrollør, mens oppdragstaker er et kartleggingsfirma. Produktspesifikasjonen bør imidlertid også kunne brukes på andre typer geodata som følger kvalitetsmodellen i standarden Geodatakvalitet <<G>>. 

Denne produktspesifikasjonen er utarbeidet iht. SOSI produktspesifikasjoner – Krav og godkjenning 5.0 <<SOSI-KRAV>>. UML-modellen som ligger til grunn for innhold i diagrammene og dokumentasjon i kap. 5, følger reglene i SOSI Regler for UML-modellering, versjon 5.1 <<SOSI-UML>>. http://sosi.geonorge.no/veiledere/UML[Denne veilederen] gir hjelp til å lese UML-diagrammene.


=== Historikk

Dette er første versjon av produktspesifikasjonen. I tidligere versjoner av FKB-generell del har det vært skissert løseslig hvordan tilbakemeldinger av avvik kan gjøres.


=== Endringslogg

Ingen endringer

=== Normative referanser

include::kap1.4.adoc[]

<<<

== Definisjoner og forkortelser

Denne produktspesifikasjonen baserer seg på definisjoner og forkortelser definert i Geodatakvalitet og FKB. Se http://sosi.geonorge.no/Standarder/FKB_generell_del/#truedefinisjoner-og-forkortelser[kapittel 5 i FKB Generell del 5.0].



<<<

== Generelt om spesifikasjonen

=== Unik identifisering
{datasett}

==== Fullstendig navn
Tilbakemelding på avvik ved kontroll av geodata

==== Versjon
5.0

=== Referansedato
2022-05-05

=== Ansvarlig organisasjon
Geovekst

=== Språk
nor

=== Hovedtema
???

=== Temakategori
basisData

=== Sammendrag
Inneholder avvik funnet ved kontroll av geodata

=== Formål
Produktspesifikasjon er laget for å ha en dokumentert og enhetlig måte å gi tilbakemelding til leverandør av kartdata nå det oppdages avvik i kontrollen av dataene hos oppdragsgiver.

=== Representasjonsform
vektor

=== Datasettoppløsning
Oppløsningen kommer an på oppløsningen på dataene som kontrolleres. Ved kontroll av FKB-data vil det være naturlig å benytte cm oppløsning i dataene.

=== Utstrekningsinformasjon

include::utstrekning.adoc[]

=== Identifikasjonsomfang
<<HeleDatasettet,Hele datasettet>>

=== Supplerende beskrivelse
Data ikke angitt

<<<

== Spesifikasjonsomfang

(Antall spesifikasjonsomfang: 1)

[[HeleDatasettet]]
=== Spesifikasjonsomfang for hele spesifikasjonen

==== Identifikasjon
Hele datasettet

==== Nivå
Datasett

==== Navn
{datasett}

==== Beskrivelse
Hele datasettet

==== Utstrekningsinformasjon

include::utstrekning.adoc[] 

<<<

== Innhold og struktur

=== Omfang
<<HeleDatasettet,Hele datasettet>>

include::kap5.adoc[]

<<<

== Referansesystem

include::kap6.adoc[]

<<<

== Kvalitet

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Beskrivelse av datakvalitet
Denne produktspesifikasjonen er laget for å bidra til bedre kontroll og bedre kvalitet på reelle geodata. Kvaliteten til avvikene som funnet ved kontroll som utveksles ved denne produktspesifikasjonen forutsettes å være god, og ved uenighet om påvisningen av de enkelte avvikene vil dette være noe som må håndteres av oppdragtaker og oppdragsgiver i fellesskap i det enkelte kartleggingsprosjekt.

<<<

== Datafangst

=== Omfang
<<HeleDatasettet,Hele datasettet>>

=== Kontroll av data
Data etter denne produktspesifikasjonen (avvik) vil oppstå ved kontroll av geodata hos oppdragsgiver. Kravene satt i avtaledokumenter og rammeverket definert i FKB <<FKB>> og Geodatakvalitet <<G>> vil definere hva som er et avvik. Denne produktspesifikasjonen gir ikke nærmere informasjon om hvordan slike avvik avdekkes, men kun om hvordan de utveksles. 

<<<

== Datavedlikehold

Ikke relevant

<<<

== Presentasjon

Ikke relevant

<<<

== Leveranse

include::kap11.adoc[]

<<<

== Tilleggsinformasjon
Ingen angitt informasjon

== Metadata

Ikke relevant

<<<


[appendix]
== GML-realisering

GML-realiseringen følger kravene i "Realisering i GML-format 5.0" <<SOSI-GML>>. Realiseringen defineres av følgende filer:

* link:{skjema-url}/Kartkontroll.xsd[GML-skjema]
* link:{skjema-url}/Kartkontroll.sch[Schematron-regler til validering av tilleggskrav til datainnhold og -struktur utover det som er definert i GML-skjemafil] (sch-fil)
* link:{skjema-url}/eksempel/[Katalog med eksempelfiler]

[appendix]
== SOSI-format-realisering

SOSI-realiseringen følger kravene i "Realisering i SOSI-format 5.0" <<SOSI-FORMAT>>. Under en utlisting av SOSI-formatrealiseringen:

include::SOSI-realisering.adoc[]

:sectnums!:

<<<

[discrete]
== Lisensvilkår

// Inkluder lisensvilkår
include::../felles/lisensvilkaar.adoc[]
